name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm ci
        
    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build:all

    - name: Test jest
      run: npm run test:cov

    - name: Test cy
      run: npm run cy:run:cov

    - name: Merge cov
      run: npm run cov:merge

    - name: Show coverage
      run: npm run cov:show

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./reports/coverage-full-total/

    - name: Comment coverage
      continue-on-error: true
      uses: danhunsaker/clover-reporter-action@v0.2.17-clover
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        clover-file: ./reports/coverage-full-total/clover.xml

    - name: Monitor coverage
      run: npm run cov:check


